# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sam-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jcz5n00dhar0"
s3_prefix = "sam-dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DynamoDBCompetitionTableName=\"tetris_competition_entry_table\" DynamoDBTableName=\"tetris_score_results_table\" DynamoDBNewsTableName=\"tetris_news_table\" DynamoDBTrainingTableName=\"tetris_training_table\" SQSName=\"score_evaluation_queue\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "sam-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-scqoc6c6uw6x"
s3_prefix = "sam-prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DynamoDBCompetitionTableName=\"tetris_competition_entry_table\" DynamoDBTableName=\"tetris_score_results_table\" DynamoDBNewsTableName=\"tetris_news_table\" DynamoDBTrainingTableName=\"tetris_training_table\" SQSName=\"score_evaluation_queue\""
image_repositories = []
