AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tetris score server resources
Parameters:
  FrontendOrigin:
    Type: String
    NoEcho: true
    Description: Enter frontend origin
  DynamoDBCompetitionTableName:
    Type: String
    Description: Enter frontend origin

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    Architectures:
      - x86_64
    Tracing: Active
    Environment:
      Variables:
        DYNAMODB_COMPETITION_TABLE_NAME: !Ref DynamoDBCompetitionTableName
  Api:
    TracingEnabled: true

Resources:
  TetrisAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: tetris_api
      StageName: tetris_api_stage
      # Cors: 
      #   AllowOrigin: !Ref FrontendOrigin

  GetEntriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./scripts
      Handler: get_entries_from_dynamodb.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBCompetitionTableName
      Events:
        GetEntriesEndpoint:
          Type: Api
          Properties:
            Path: /entries
            Method: get
            RestApiId: !Ref TetrisAPI

# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # HelloWorldFunction:
  #   Description: Hello World Lambda Function ARN
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: Implicit IAM Role created for Hello World function
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
