version: '1'

services:
  server:
    container_name: tetris_server_container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - type: bind
        source: "./server"
        target: "/server"
    env_file: .env
    tty: true