FROM python:3.10-bullseye
RUN apt-get update && apt-get install -y \
    xvfb
ENV PYTHONUNBUFFERED 1
ENV QT_QPA_PLATFORM offscreen
RUN mkdir /server
WORKDIR /server
ADD ../server .
RUN pip install -r requirements.txt
ENTRYPOINT make polling