test:
	python manage.py test score_evaluation.tests

# command for start
# `python manage.py start ${interval}`
start:
	python manage.py start 60

test-entries:
	python manage.py test_entries entries.csv
