test:
	python manage.py test score_evaluation.tests

# command for start polling
# `python manage.py polling ${interval}`
polling:
	python manage.py polling 60

test-entries:
	python manage.py test_entries entries.csv
